version: '3.8'

services:
  # 1. MongoDB Database Container (Pehle yeh chalega)
  mongodb:
    image: mongo:latest
    container_name: school-db-local
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # 2. Backend Container
  app-backend:
    build: ./backend
    container_name: school-backend
    ports:
      - "5000:5000"
    environment:
      # Is bar hum Atlas nahi, balki local container ka naam use karenge
      - MONGO_URI=mongodb://mongodb:27017/schoolDB
    depends_on:
      - mongodb

  # 3. Frontend Container
  app-frontend:
    build: ./frontend
    container_name: school-frontend
    ports:
      - "8080:8080"

volumes:
  mongo-data:
